### ISSUE TITLE
Feat: Make a landing page after clicking submit 

### ISSUE THREAD

**Issue by AdityaSinha2305** [AdityaSinha2305/ForkTheCaptcha#25]
Create a login page so that once user submitted the valid captcha it should redirect to that login page.

**Comment by Nitinkumar-29** [comment]
Hey, I would like to work on this, can you please assign me this one

**Comment by kshitijakarsh** [comment]
Removing extra buttons and adding redirection features makes the captcha clear.

Assign this to me so that I can make these UI changes and add redirection.

https://github.com/user-attachments/assets/57720c71-fed3-49d7-9b8a-866f1a75d092

**Comment by AdityaSinha2305** [comment]
@kshitijakarsh That extra button is for voice recognition.
The redirection page is good but before that there should be a confirmation message for the captcha.

**Comment by kshitijakarsh** [comment]
@AdityaSinha2305 I didn't remove the confirmation message part, when submit button is clicked we get the automated speech saying "Valid Captcha" and after a timeout of 2 seconds, the login page gets loaded. Is there anything else that you're trying to use the "Start" button for? Please specify so that I can get better understanding of it.
